version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    image: 'notepurin'
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3307:3306"
    environment:
       MYSQL_DATABASE: 'notepurin'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql